### ISSUE TITLE
I don't understand how this weight is set, MAX_POINTS is set according to what，

### ISSUE THREAD

**Issue by hutingz** [jokofa/torch_kmeans#1]

**Comment by jokofa** [comment]
Hi, thanks for opening the issue. If I understand your question correctly, then you men the MAX_POINTS parameter used in the constrained_kmeans jupyter notebook?
There that value is just used to normalize the weights to simulate the case where you do not have real valued weights but just a limit on the NUMBER of points per cluster. That means it is a user provided parameter, i.e. how many points you want to allow per cluster. Then, if you take weights of one and divide by the max number of points per cluster, the constraint of sum(weights) < = 1
will enforce that at maximum MAX_POINTS are assigned to the same cluster. 

Does that answer your question?

**Comment by hutingz** [comment]
Thank you very much for your reply.
　　Ｎｏｗ，I have another question about gpu utilization, when I don't use ConstrainedKMeans() in the program, the GPU utilization is quite high, once I use ConstrainedKMeans(), the GPU utilization hovers around 20%.Step through debugging and find that the data is on cuda, so I don't understand why this function makes GPU utilization so low．




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jokofa/torch_kmeans"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月5日(星期六) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jokofa/torch_kmeans] I don't understand how this weight is set, MAX_POINTS is set according to what， (Issue #1)





 
Hi, thanks for opening the issue. If I understand your question correctly, then you men the MAX_POINTS parameter used in the constrained_kmeans jupyter notebook?
 There that value is just used to normalize the weights to simulate the case where you do not have real valued weights but just a limit on the NUMBER of points per cluster. That means it is a user provided parameter, i.e. how many points you want to allow per cluster. Then, if you take weights of one and divide by the max number of points per cluster, the constraint of sum(weights) < = 1
 will enforce that at maximum MAX_POINTS are assigned to the same cluster.
 
Does that answer your question?

**Comment by jokofa** [comment]
I did not completely log and check the GPU utilization, but this could be because of the constrained assignment in the constrained kmeans procedure, which has to be executed sequentially and therefore is limited in its GPU utilization ([this for loop](https://github.com/jokofa/torch_kmeans/blob/876908977f1a23ef0bcbc89cc31ee62581a260c4/src/torch_kmeans/clustering/constr_kmeans.py#L333l)
), while the assignment for standard kmeans can be done in parallel on the GPU.
