### ISSUE TITLE
KMeans

### ISSUE THREAD

**Issue by thirteenl** [jokofa/torch_kmeans#7]
Hello, I would like to ask a question. I now have 35,000 images and feed them into the convolutional neural network in batches to obtain its features. The obtained feature dimensions are (32,512,2,2). When I use KMeans algorithm, does the parameter BS refer to the size of Batch_Size of my input data. If so what does N correspond to?
Here is my code to process the data.
```
def deep_clustering(model, dataloader, k):
    features = []
    original_labels = []
    for inputs, labels in dataloader:
        with torch.no_grad():  # 
            outputs = model(inputs)  # VGG->(32,512,2,2)
```

**Comment by jokofa** [comment]
Hi there, 
sorry for the late reply, I was quite busy the last few weeks.

The dimensions of the input correspond to the following:
BS = batch size
N = number of points/nodes/objects (sample size)
...  spatial dimension

in case of images you usually have 3 spatial dimensions: height, width and channel.
In case of your embedded images it depends on how your feature dimension is defined.
if 32 is the batch size and each image is a feature representation of (512, 2,2) then you most likely need to flatten the embedding vector 
(512, 2, 2) --> (2048, )
I hope that helps.
