### ISSUE TITLE
Some questions about the Useage 

### ISSUE THREAD

**Issue by robert1818118** [jokofa/torch_kmeans#8]
Can this toolkit be used for model forward process?

**Comment by jokofa** [comment]
yes, the  [soft kmeans algorithm](https://torch-kmeans.readthedocs.io/en/latest/api/torch_kmeans.html#torch_kmeans.SoftKMeans) is differentiable through the fixed points.
Please see the corresponding [paper](https://arxiv.org/abs/1905.13732).

**Comment by robert1818118** [comment]
Thanks a lot, my problem has been solved! This package is convenient and excellent!

**Comment by robert1818118** [comment]
> yes, the [soft kmeans algorithm](https://torch-kmeans.readthedocs.io/en/latest/api/torch_kmeans.html#torch_kmeans.SoftKMeans) is differentiable through the fixed points. Please see the corresponding [paper](https://arxiv.org/abs/1905.13732).

Thanks a lot, my problem has been solved! This package is convenient and excellent!

**Comment by robert1818118** [comment]
Thanks a lot, my problem has been solved! This package is convenient and excellent!
发件人: jokofa
发送时间: 2023年11月23日 18:54
收件人: jokofa/torch_kmeans
抄送: Xiao JH; Author
主题: Re: [jokofa/torch_kmeans] Some questions about the Useage (Issue #8)

Closed #8 as completed.
